
import React from 'react'
import Head from 'next/head'
import { useRouter } from 'next/router'
export default function Home() {
  const router = useRouter()
  const registerUser = async event => {
    event.preventDefault()

    const res = await fetch(
        'http://localhost:8080/api/cv',
        {
            body: JSON.stringify({
                first_name: event.target.first_name.value,
                last_name: event.target.last_name.value,
                gender: event.target.gender.value,
                email: event.target.email.value,
                mobile_phone: event.target.mobile_phone.value,
                birth_date: event.target.birth_date.value,
                position: event.target.position.value,
                expected_salary: event.target.expected_salary.value,
                previous_salary: event.target.previous_salary.value,
                location: event.target.location.value,
                refferal_by: event.target.refferal_by.value
            }),
            headers: {
                'Content-Type': 'application/json'
            },
            allowedHeaders: [
                'Content-Type',
            ],
            method: 'POST'
        }
    )

    const result = await res.json()
    console.log(result)
    event.target.reset()
    router.push('/thank-you')
    // result.user => 'Ada Lovelace'
}

  return (
    <div >
      <Head>
          <title>Simple CV with React Express Mongo</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Generated by create next app for testing code AIA" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className="row">
          <div className="col row align-items-center" style={{ backgroundColor: '#003059', color: '#ffffff', height:'100vh',textAlign:'center'}}>
            <h3>Simple CV <br />Build with Next Express and Mongodb</h3>
          </div>
          <div className="col right-box" style={{ height:'100vh', overflow:'auto'}}>
            <form onSubmit={ registerUser } style={{ padding:'50px 15%'}}>
              <div className="mb-3">
                <label className="form-label">First Name</label>
                <input type="text" name="first_name" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Last Name</label>
                <input type="text" name="last_name" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Gender</label>
                <select className="form-control form-control-sm" name="gender" required>
                  <option value="">..Select Gender..</option>
                  <option value="Male">Male</option>
                  <option value="Female">Female</option>
                </select>
              </div>
              <div className="mb-3">
                <label className="form-label">Email</label>
                <input type="email" name="email" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Mobile Phone</label>
                <input type="text" name="mobile_phone" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Birth Date</label>
                <input type="date" name="birth_date" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Apply For Position</label>
                <input type="text" name="position" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Expected Salary</label>
                <input type="text" name="expected_salary" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Previous Salary</label>
                <input type="text" name="previous_salary" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Location</label>
                <input type="text" name="location" className="form-control form-control-sm" required />
              </div>
              <div className="mb-3">
                <label className="form-label">Refferal By</label>
                <input type="text" name="refferal_by" className="form-control form-control-sm" required />
              </div>
              {/* <div className="mb-3">
                <label className="form-label">CV Upload</label>
                <input type="file" name="last_name" className="form-control form-control-sm" required />
              </div> */}
              <div className="col-auto">
                <button type="submit" className="btn btn-primary mb-3">Submit</button>
              </div>
            </form>
          </div>
        </div>
      </div>
      
    </div>
  )
}

