
import React from 'react'
import Head from 'next/head'
export default function ThankYou() {
  return (
    <div >
      <Head>
          <title>Simple CV with React Express Mongo</title>
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <meta name="description" content="Generated by create next app for testing code AIA" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container-fluid">
        <div className="row">
          <div className="col row align-items-center" style={{ backgroundColor: '#003059', color: '#ffffff', height:'100vh',textAlign:'center'}}>
            <h3>Simple CV <br />Build with Next Express and Mongodb</h3>
          </div>
          <div className="col row align-items-center text-center" style={{ height:'100vh', overflow:'auto'}}>
            <h3>
                Thank you for your submit <br />
                <small className="text-muted">We will contact you as soon as possible</small>
            </h3>
          </div>
        </div>
      </div>
      
    </div>
  )
}

